package project_1;

/**
 * This class is for CGPA and total credit hours for
 * all semesters display.
 * 
 * @author [redacted]
 * @version [redacted]
 * @since [redacted]
 */
public class cgpa_gui extends javax.swing.JFrame {

    /**
     * Creates new form cgpa_gui
     */
    public cgpa_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cgpaLabel = new javax.swing.JLabel();
        totalCreditHoursFinalTF = new javax.swing.JTextField();
        totalCreditHoursFinalLabel = new javax.swing.JLabel();
        cgpaTF = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        gpaTableScrollPane = new javax.swing.JScrollPane();
        gpaTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GPA and CGPA calculation");
        setLocation(new java.awt.Point(600, 300));
        setMinimumSize(new java.awt.Dimension(825, 535));
        setName("cgpa_frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(825, 535));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cgpaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cgpaLabel.setText("CGPA  :  ");
        getContentPane().add(cgpaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        totalCreditHoursFinalTF.setEditable(false);
        totalCreditHoursFinalTF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalCreditHoursFinalTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(totalCreditHoursFinalTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 200, -1));

        totalCreditHoursFinalLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalCreditHoursFinalLabel.setText("Total credit hours  :  ");
        getContentPane().add(totalCreditHoursFinalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        cgpaTF.setEditable(false);
        cgpaTF.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cgpaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cgpaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 200, -1));

        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 200, 50));

        gpaTable.setAutoCreateRowSorter(true);
        gpaTable.setBackground(new java.awt.Color(214, 217, 223));
        gpaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sem No.", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gpaTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        gpaTableScrollPane.setViewportView(gpaTable);

        getContentPane().add(gpaTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 300, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // EXIT
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if(evt.getSource()==exitButton)
        {
            // exit on end program
            dispose();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cgpaLabel;
    public javax.swing.JTextField cgpaTF;
    private javax.swing.JButton exitButton;
    public javax.swing.JTable gpaTable;
    private javax.swing.JScrollPane gpaTableScrollPane;
    private javax.swing.JLabel totalCreditHoursFinalLabel;
    public javax.swing.JTextField totalCreditHoursFinalTF;
    // End of variables declaration//GEN-END:variables
}
