package project_1;

import javax.swing.*;

/**
 * This class is to show the main menu, asking for Program name
 * and total no of semesters.
 * 
 * @author [redacted]
 * @version [redacted]
 * @since [redacted]
 */
public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu.
     **/
    public main_menu() {
        initComponents();
    }
    
    public String program = " ";
    public int sem_no = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sem_noLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        sem_noTF = new javax.swing.JTextField();
        programLabel1 = new javax.swing.JLabel();
        programTF = new javax.swing.JTextField();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GPA and CGPA calculator");
        setLocation(new java.awt.Point(600, 300));
        setPreferredSize(new java.awt.Dimension(850, 425));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sem_noLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sem_noLabel.setText("Total no. of sem.  :  ");
        getContentPane().add(sem_noLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        titleLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel1.setText("GPA and CGPA calculator");
        getContentPane().add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        sem_noTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(sem_noTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 370, 40));

        programLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        programLabel1.setText("Program  :  ");
        getContentPane().add(programLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        programTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(programTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 370, 40));

        continueButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        continueButton.setText("Continue");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(continueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 230, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This function is start gpa_gui after receiving correct inputs from user.
     * 
     * @param evt on click
     */
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        if(evt.getSource()==continueButton)
        {
            // if theres no input in either TF
            if (sem_noTF.getText().length() == 0 || programTF.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(
                    null,
                    "One or more inputs are empty!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
            }
            // else if fulled
            else
            {
                // try...catch for hand. excep.
                try
                {
                    // get text from TF to vars below
                    program = programTF.getText();
                    sem_no = Integer.parseInt(sem_noTF.getText());

                    // if sem_no out of range 1-10
                    if(sem_no <= 0 || sem_no > 10)
                    {
                        sem_noTF.setText("");
                        
                        // error msg. notifying users
                        JOptionPane.showMessageDialog(
                            null,
                            "Invalid total no. of semesters!",
                            "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                    // else if sem_no in range
                    else
                    {
                        // delete current frame instance
                        dispose();
                        
                        // create new gpa_gui instance
                        java.awt.EventQueue.invokeLater(() -> {
                        gpa_gui g1 = new gpa_gui();

                        g1.setVisible(true);
                        
                        // set programLabel in g1 from this program
                        g1.programLabel.setText("Program  :  " + program);

                        // update count_sem in g1
                        g1.count_sem += 1;
                        
                        // set semLabel with plus count_sem
                        g1.semLabel.setText("Semester  :  " + Integer.toString(g1.count_sem));

                        // set g1's sem_no equal to this sem_no
                        // propaply couldve been done better..
                        g1.sem_no = sem_no;
                        });
                    }
                }
                catch (NumberFormatException a_error)
                {
                    sem_noTF.setText("");
                    
                    // error msg. notifying users
                    JOptionPane.showMessageDialog(
                    null,
                    "Invalid total no. of semesters!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new main_menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel programLabel1;
    private javax.swing.JTextField programTF;
    private javax.swing.JLabel sem_noLabel;
    private javax.swing.JTextField sem_noTF;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
